FROM apache/beam_python3.11_sdk:2.62.0

# Set the working directory in the container
WORKDIR /app

# Copy the pipeline code into the container
COPY ./python-beam/streaming-token-usage.py /app/

# Install Java (e.g., OpenJDK 11)
RUN apt-get update && apt-get install -y openjdk-11-jdk && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Set JAVA_HOME
ENV JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
ENV PATH=$JAVA_HOME/bin:$PATH

# Install any additional dependencies here
RUN pip install apache-beam[flink,kafka]

# Set environment variables for Kafka configuration
ENV BOOTSTRAP_SERVERS="broker:29092"
ENV INPUT_TOPIC="otlp-metrics-json"
ENV OUTPUT_TOPIC="token-usage"

# Set the default command to run the pipeline
CMD ["python", "streaming-token-usage.py", \
     "--bootstrap_servers=${BOOTSTRAP_SERVERS}", \
     "--input-topic=${INPUT_TOPIC}", \
     "--output-topic=${OUTPUT_TOPIC}"]