# Beam SDK worker for Python 3.8 and Beam 2.46.0
FROM apache/beam_python3.8_sdk:2.46.0

# Set the working directory in the container
WORKDIR /app

# Copy the pipeline code into the container
COPY ./python-beam/streaming-token-usage.py /app/

# Install any additional dependencies here
RUN pip install apache-beam[flink,kafka]

# Set environment variables for Kafka configuration
ENV BOOTSTRAP_SERVERS="broker:29092"
ENV INPUT_TOPIC="otlp-metrics-json"
ENV OUTPUT_TOPIC="token-usage"

# Set the default command to run the pipeline
CMD ["python", "streaming-token-usage.py", \
     "--bootstrap_servers=${BOOTSTRAP_SERVERS}", \
     "--input-topic=${INPUT_TOPIC}", \
     "--output-topic=${OUTPUT_TOPIC}"]