receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"  # Binds gRPC to all interfaces on port 4317
      http:
        endpoint: "0.0.0.0:4318"  # Binds HTTP to all interfaces on port 4318

processors:
  batch: {}

exporters:
  kafka:
    brokers: ["broker:29092"]
    protocol_version: "2.0.0"    # Specify Kafka protocol version
    topic: "otlp-metrics"        # Kafka topic to publish metrics to
    encoding: "otlp_proto"       # Format for exporting (e.g., otlp_proto)
  debug:
    verbosity: "detailed"        # This prints detailed output of the received metrics

service:
  telemetry:
    logs:
      level: debug             # Sets the Collector's log level to debug
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, kafka]  # Both exporting to Kafka and printing metrics via debug exporter