receivers:
  otlp:
    protocols:
      http:
      grpc:

processors:
  batch:

exporters:
  kafka:
    brokers: ["broker:9092"]
    protocol_version: "2.0.0"    # Specify Kafka protocol version
    topic: "otlp-metrics"       # Kafka topic to publish metrics to
    encoding: "otlp_proto"      # Format for exporting (e.g., otlp_proto)
    authentication: {}
  
service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [kafka]